package com.humber.j2ee.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.humber.j2ee.model.Dish;
import com.humber.j2ee.repository.DishRepository;

@Service
public class DishService {

	@Autowired
	private DishRepository dishRepository;
	
//	findAll () and other methods is auto generated by Spring Boot (jpa repository in DishRepository)
	public List<Dish> getDishes() {
		return this.dishRepository.findAll();
	}

//	method to get dish by name
//	public Optional<Dish> findDishByName(String name) {
//		return this.dishRepository.findById(1)
//	}

}
